export const ADD_TO_CART = 'ADD_TO_CART'
export const CLEAR_PANIER = 'CLEAR_PANIER'
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'
export const REMOVE_ITEM_FROM_PANIER = 'REMOVE_ITEM_FROM_PANIER'
 

