export const CREATE_COMMANDE = 'CREATE_COMMANDE';
export const SET_CURRENT_COMMANDE_REQUEST = 'SET_CURRENT_COMMANDE_REQUEST';
export const CLEAR_CURRENT_COMMANDE = 'CLEAR_CURRENT_COMMANDE';

export const GET_COMMANDE = 'GET_COMMANDE';
export const GET_LIST_COMMANDES = 'GET_ALL_COMMNADES';
export const SET_SELECTED_COMMANDE = 'SET_SELECTED_COMMANDE';
export const SET_LIST_COMMNADES = 'SET_ALL_COMMNADES';