export const LIST_PRODUCTS = 'LIST_PRODUCTS'
export const SET_PRODUITS = 'SET_PRODUITS'
export const SORT_PRODUCT_BY_PRICE = 'SORT_PRODUCT_BY_PRICE'
export const FILTER_PRODUCT_BY_PRICE_INTERVAL = 'FILTER_PRODUCT_BY_PRICE_INTERVAL'
export const FILTER_PRODUCT_COLOR = 'FILTER_PRODUCT_COLOR'
export const FILTER_PRODUCT_BY_CATEGORIE =  'FILTER_PRODUCT_BY_CATEGORIE' 


